### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [aprazdnikov/gistools#1]
You can load a GPX as a vector layer in QGIS and convert it to a Mapinfo file using native QGIS. What functionality does this plugin offer that is not in core ?

**Comment by aprazdnikov** [comment]
Automation of the process of converting several GPX format files to MapInfo TAB. The user only needs to select the directory with the GPX files and start the conversion. Mapinfo directory with data will be created in the same directory.

**Comment by aprazdnikov** [comment]
> You can load a GPX as a vector layer in QGIS and convert it to a Mapinfo file using native QGIS. What functionality does this plugin offer that is not in core ?

Automation of the process of converting several GPX format files to MapInfo TAB. The user only needs to select the directory with the GPX files and start the conversion. Mapinfo directory with data will be created in the same directory.

**Comment by NyakudyaA** [comment]
@aprazdnikov Can you please update your description to let people know what it does. From the current description it doesn't really help users want to download your plugin

**Comment by aprazdnikov** [comment]
@NyakudyaA Ok. I have updated the description.

**Comment by NyakudyaA** [comment]
I have approved, just as a feature request maybe you could also offer the ability to bulk convert other formats ie kml etc

**Comment by aprazdnikov** [comment]
Of course, in the future, I will add different formats, such as KML, SHP and others
