### ISSUE TITLE
Plugin version 0.3 approved

### ISSUE THREAD

**Issue by aprazdnikov** [aprazdnikov/gistools#3]
I have uploaded a new version of the plugin. Can you make a confirmation?
https://plugins.qgis.org/plugins/gistools/

@NyakudyaA

**Comment by NyakudyaA** [comment]
Hi @aprazdnikov you do not need to ping me when you upload a new version. I will get a notification and approve during my free time. Plugin management is a pro bono exercise

**Comment by aprazdnikov** [comment]
Ok
